name: Android CI Workflow

on:
  push:
    branches:
      - release
    tags:
      - 'v1.0.*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: New Tag Generator test
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          CURRENT_TAG=$(curl --silent "https://api.github.com/repos/MortyN/MOB3000_FrisbeeGolf/releases/latest" | # Get latest release from GitHub api
          grep '"tag_name":' |                                            # Get tag line
          sed -E 's/.*"([^"]+)".*/\1/')
          NEWVERSION=`expr ${CURRENT_TAG: -1} + 1`
          NEWTAG=${CURRENT_TAG%?}$NEWVERSION
          echo "::set-env name=NEWTAG::${CURRENT_TAG%?}$NEWVERSION"
      - name: Checkout ${{env.NEWTAG}}
        uses: actions/checkout@v1
      - name: Setup JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Tests
        run: bash ./gradlew test --stacktrace   
  apk:
    name: Generate APK 
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk 
  release:
    name: Release APK
    needs: apk
    # add semantic tagging strategy later
    # if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Generate new tag
        run: |
          CURRENT_TAG=$(curl --silent "https://api.github.com/repos/MortyN/MOB3000_FrisbeeGolf/releases/latest" | # Get latest release from GitHub api
          grep '"tag_name":' |                                            # Get tag line
          sed -E 's/.*"([^"]+)".*/\1/')
          NEWVERSION=`expr ${CURRENT_TAG: -1} + 1`
          echo "::set-env name=NEWTAG::${CURRENT_TAG%?}$NEWVERSION"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.NEWTAG}}
          release_name: Release ${{env.NEWTAG}}
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-debug.apk
          asset_name: Disky.apk
          asset_content_type: application/zip
